services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest_starter_dev
    env_file:
      - .env
    environment:
      TZ: ${TZ:-Europe/Moscow}
      NODE_ENV: development
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/app:cached
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: npm run dev
