FROM node:24-slim

WORKDIR /app

ENV TZ=Europe/Moscow

RUN apt-get update \
    && apt-get install -y --no-install-recommends tzdata procps openssl ca-certificates \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm ci
